# Generated by Django 4.0.4 on 2022-05-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='gallery.category'),
        ),
    ]
