# Generated by Django 4.0.4 on 2022-05-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Entertainment', 'Entertainment')], max_length=30),
        ),
    ]
