# Generated by Django 4.0.4 on 2022-05-27 04:30

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63, null=True)),
            ],
        ),
    ]
