# Generated by Django 4.0.4 on 2022-05-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_image_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tags',
            new_name='tag',
        ),
    ]
