# Generated by Django 4.0.4 on 2022-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_rename_tags_image_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
